baseURL = "https://unmuteable.com"
languageCode = "en-us"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  blog = "/:year/:month/:slug/"
  page = "/:slug/"

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[params]
  company = "Unmuteable"
  title = "UN ✕ MUTE ✕ ABLE"
  tagline = "Measuring the impact of blockchain and decentralization on society and culture"
  description = "A publication centered around crypto, privacy, decentralization, and the people making it happen."
  copyright = "© 2020 UNMUTEABLE"

[params.author]
  name = "Jason Schrader"
  github = "https://github.com/whoabuddy"
  sitename = "UNMUTEABLE"
  twitter = "@theunmuteable"

# used for SEO image tags in head
[params.logo]
  img = "img/Unmuteable_Logo_Sticker_Social.png"
  type = "image/png"
  width = "800"
  height = "400"
  alt = "A large X covered with three rows of letters that spell UNMUTEABLE"

[params.palette]
  primary = "#00CCCC"
  primary_lt = "#64FFFF"
  primary_dk = "#009A9B"
  on_primary = "#000000"
  secondary = "#808080"
  secondary_lt = "#AFAFAF"
  secondary_dk = "#545454"
  on_secondary = "#000000"
  background = "#FFFFFF"
  on_background = "#191D26"
  surface = "#FFFFFF"
  on_surface = "#191D26"
  error = "#FFFFFF"
  on_error = "#CC0000"

[params.palette.darkmode]
  background = "#191D26"
  on_background = "#AFAFAF"
  surface = "#191D26"
  on_surface = "#AFAFAF"
  error = "#CC0000"
  on_error = "#FFFFFF"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Articles"
    identifier = "blog"
    url = "/blog/"
    weight = 30
  [[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 40
  [[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact/"
    weight = 50
