baseURL = "https://unmuteable.com"
languageCode = "en-us"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"

[params]
  company = "Unmuteable"
  title = "UN ✕ MUTE ✕ ABLE"
  tagline = "Measuring the impact of blockchain and decentralization on society and culture"
  description = "A publication centered around crypto, privacy, decentralization, and the people making it happen."
  copyright = "© 2020 UNMUTEABLE"

# used for og:image tags in head
[params.logo]
  img = "img/Unmuteable_Logo_Square_Color.png"
  type = "image/png"
  width = "150"
  height = "150"
  alt = "The square unmuteable logo with a large letter U and a small letter X situated at the top-right corner of the letter U."

[params.palette]
  primary = "#00CCCC"
  primary_lt = "#64FFFF"
  primary_dk = "#009A9B"
  on_primary = "#000000"
  secondary = "#808080"
  secondary_lt = "#AFAFAF"
  secondary_dk = "#545454"
  on_secondary = "#000000"
  background = "#FFFFFF"
  on_background = "#191D26"
  surface = "#FFFFFF"
  on_surface = "#191D26"
  error = "#FFFFFF"
  on_error = "#CC0000"

[params.palette.darkmode]
  background = "#191D26"
  on_background = "#AFAFAF"
  surface = "#191D26"
  on_surface = "#AFAFAF"
  error = "#CC0000"
  on_error = "#FFFFFF"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = "20"
  [[menu.main]]
    name = "Articles"
    identifier = "blog"
    url = "/blog/"
    weight = "30"
  [[menu.main]]
    name = "Login"
    identifier = "admin"
    url = "/admin"
    weight = 50
