baseURL = "https://unmuteable.com"
theme = "hugo-unmuteable"
languageCode = "en-us"

[params]
  company = "Unmuteable"
  title = "UN ✕ MUTE ✕ ABLE"
  description = "A publication centered around crypto, privacy, decentralization, and the people making it happen."
  copyright = "©2020 UN ✕ MUTE ✕ ABLE"

[params.logo]
  img = "img/Unmuteable-150x150.png"
  type = "image/png"
  width = "150"
  height = "150"
  alt = "Logo with the letter U and a superscript letter X that represent a shortened version of Unmuteable."

[params.palette]
  primary = "#00CCCC"
  primary_lt = "#64FFFF"
  primary_dk = "#009A9B"
  on_primary = "#000000"
  secondary = "#808080"
  secondary_lt = "#AFAFAF"
  secondary_dk = "#545454"
  on_secondary = "#000000"
  background = "#FFFFFF"
  on_background = "#191D26"
  surface = "#FFFFFF"
  on_surface = "#191D26"
  error = "#FFFFFF"
  on_error = "#CC0000"

[params.palette.darkmode]
  background = "#191D26"
  on_background = "#AFAFAF"
  surface = "#191D26"
  on_surface = "#AFAFAF"
  error = "#CC0000"
  on_error = "#FFFFFF"
