baseURL = "https://unmuteable.com"
theme = "hugo-unmuteable"
languageCode = "en-us"

[params]
  company = "Unmuteable"
  title = "UN✕MUTE✕ABLE"
  description = "A publication centered around crypto, privacy, decentralization, and the people making it happen."
  copyright = "©2020 UN✕MUTE✕ABLE"

[params.logo]
  img = "img/Unmuteable-150x150.png"
  type = "image/png"
  width = "150"
  height = "150"
  alt = "Logo with the letter U and a superscript letter X that represent a shortened version of Unmuteable."

[params.palette]
  primary = "#00CCCC"
  secondary = "#808080"
  dark = "#191D26"
  light = "#FFFFFF"
