baseURL = "https://unmuteable.com"
theme = "hugo-unmuteable"
languageCode = "en-us"
sectionPagesMenu = "main"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"

[params]
  company = "Unmuteable"
  title = "UN ✕ MUTE ✕ ABLE"
  description = "A publication centered around crypto, privacy, decentralization, and the people making it happen."
  copyright = "© 2020 UNMUTEABLE"

[params.logo.primary]
  img = "img/Unmuteable_Primary_Logo.png"
  img_dk = "img/Unmuteable_Primary_Logo_DarkMode.png"
  type = "image/png"
  width = "1200"
  height = "230"
  alt = "A logo with the word unmuteable separated in three parts by an X symbol."

[params.logo.secondary]
  img = "img/Unmuteable_Secondary_Logo.png"
  img_dk = "img/Unmuteable_Secondary_Logo_Darkmode.png"
  type = "image/png"
  width = "150"
  height = "150"
  alt = "A logo with the letter U and a superscript letter X that represent a shortened version of Unmuteable."

[params.logo.tertiary]
  img = "img/Unmuteable_Tertiary_Logo.png"
  img_dk = "img/Unmuteable_Tertiary_Logo_Darkmode.png"
  type = "image/png"
  width = "150"
  height = "150"
  alt = "A logo with the word unmuteable over the top of an X symbol."

[params.palette]
  primary = "#00CCCC"
  primary_lt = "#64FFFF"
  primary_dk = "#009A9B"
  on_primary = "#000000"
  secondary = "#808080"
  secondary_lt = "#AFAFAF"
  secondary_dk = "#545454"
  on_secondary = "#000000"
  background = "#FFFFFF"
  on_background = "#191D26"
  surface = "#FFFFFF"
  on_surface = "#191D26"
  error = "#FFFFFF"
  on_error = "#CC0000"

[params.palette.darkmode]
  background = "#191D26"
  on_background = "#AFAFAF"
  surface = "#191D26"
  on_surface = "#AFAFAF"
  error = "#CC0000"
  on_error = "#FFFFFF"
